language: python
python:
  - "3.6"
install:
    # - easy_install distribute
    - pip install --allow-all-external -r requirements.txt
    - pip install pep8
script:
    - find . -name \*.py -exec pep8 {} +
