language: python
python:
  - "3.6"
before_install:
    - pip freeze > requirements.txt
    - pip install -r requirements.txt
install:
    - pip install pep8
script:
    # - find . -name \*.py -exec pep8 {} +
    - pep8 --show-source classification_machine/
